version: '3.8'

services:
  # ========== MONOLITO==========
  monolith-api:
    build: ./monolith
    container_name: monolith-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/monolith_db
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - monolith-network
    restart: unless-stopped

  # ========== BD ==========
  postgres:
    image: postgres:16-alpine
    container_name: monolith-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monolith_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - monolith-network
    restart: unless-stopped

networks:
  monolith-network:
    driver: bridge

volumes:
  postgres_data: